# Generated by Django 3.0.1 on 2022-04-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20220422_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
